First week
Dev-incubator/WebAutopark.Artem_Kondratovich pull request #1
Opened 2022-01-03 10:10 UTC by Kondratovich

2022-01-04 12:07 UTC, kuzmiich requested changes

2022-01-04 12:07 UTC, kuzmiich commented on WebAutopark.DatabaseAccess/WebAutopark.DatabaseAccess.csproj
> +  <ItemGroup>
Why you don't install package dapper?

2022-01-04 12:07 UTC, kuzmiich commented on WebAutopark.DatabaseAccess/SQLScripts/CreateDbScript.sql
> +	[VehicleId] INT FOREIGN KEY REFERENCES Vehicles(VehicleId)
Foreign and primary key should be on Table lvl as constraint

2022-01-04 12:07 UTC, kuzmiich commented on WebAutopark.DatabaseAccess/Repositories/VehicleTypeRepository.cs
> +        public void Delete(int id) => Connection.Execute(QueryDelete, id);
Incorrect parameter `id` in Execute method

2022-01-04 12:07 UTC, kuzmiich commented on WebAutopark.DatabaseAccess/Repositories/VehicleRepository.cs
> +        public void Delete(int id) => Connection.Execute(QueryDelete, id);
Incorrect parameter `id` in Execute method

2022-01-04 12:17 UTC, Kondratovich commented on WebAutopark.DatabaseAccess/Repositories/ComponentRepository.cs
> +        public void Delete(int id) => Connection.Execute(QueryDelete, id);
fixed

2022-01-04 12:18 UTC, Kondratovich commented on WebAutopark.DatabaseAccess/Repositories/OrderRepository.cs
> +        public void Delete(int id) => Connection.Execute(QueryDelete, id);
fixed

2022-01-04 12:18 UTC, Kondratovich commented on WebAutopark.DatabaseAccess/WebAutopark.DatabaseAccess.csproj
> +  <ItemGroup>
fixed

2022-01-04 12:18 UTC, Kondratovich commented on WebAutopark.DatabaseAccess/Repositories/VehicleTypeRepository.cs
> +        public void Delete(int id) => Connection.Execute(QueryDelete, id);
fixed

2022-01-04 12:18 UTC, Kondratovich commented on WebAutopark.DatabaseAccess/Repositories/VehicleRepository.cs
> +        public void Delete(int id) => Connection.Execute(QueryDelete, id);
fixed

2022-01-04 13:29 UTC, Kondratovich commented on WebAutopark.DatabaseAccess/SQLScripts/CreateDbScript.sql
> +	[VehicleId] INT FOREIGN KEY REFERENCES Vehicles(VehicleId)
Fixed, but can you explain the benefits of declaring foreign and primary keys on table lvl as constraint?)

2022-01-04 13:34 UTC, Kondratovich commented on WebAutopark.Core/Entities/Order.cs
> +    public class Order
![image](https://user-images.githubusercontent.com/58659395/148066348-9865c05c-61f9-4cbd-817f-78775633e76c.png)
Why? Database schema from specification has only 2 fields in Orders table

2022-01-04 13:41 UTC, Kondratovich commented on WebAutopark.DatabaseAccess/Repositories/OrderItemRepository.cs
> +        private readonly string QueryCreate = "INSERT INTO OrderItems (OrderId, ComponentId, Quantity) " +
I understand that Id's is better to auto-increment if possible, but in this case the fields "OrderId", "ComponentId" are foreign keys and I don't quite understand why to increment them)

2022-01-04 15:02 UTC, kuzmiich commented on WebAutopark.DatabaseAccess/Repositories/OrderItemRepository.cs
> +        private readonly string QueryCreate = "INSERT INTO OrderItems (OrderId, ComponentId, Quantity) " +
All right.
I miss this case)

2022-01-04 15:04 UTC, kuzmiich commented on WebAutopark.DatabaseAccess/SQLScripts/CreateDbScript.sql
> +	[VehicleId] INT FOREIGN KEY REFERENCES Vehicles(VehicleId)
It's the rule of write SQL scripts.
Read MSDN.

2022-01-04 15:26 UTC, kuzmiich commented on WebAutopark.Core/Entities/Order.cs
> +    public class Order
Ok, don't change anything
When I created this database, I don't have db sheme.

2022-01-04 15:27 UTC, kuzmiich approved these changes
Good job

2022-01-04 23:42 UTC, ArtyomKolosov2 approved these changes

2022-01-05 10:13 UTC, PushMeNow approved these changes

2022-01-07 14:31 UTC, merged