Third week
Dev-incubator/WebAutopark.Artem_Kondratovich pull request #3
Opened 2022-01-16 11:13 UTC by Kondratovich

2022-01-16 19:43 UTC, kuzmiich requested changes

2022-01-16 19:43 UTC, kuzmiich commented on WebAutopark.Core/Entities/Vehicle.cs
> +        public int VehicleId { get; set; }
```suggestion
        public int VehicleTypeId { get; set; }
```

2022-01-16 19:43 UTC, kuzmiich commented on WebAutopark/Controllers/VehicleController.cs
> +        public ActionResult Create()
Add attribute pls.

2022-01-16 19:43 UTC, kuzmiich commented on WebAutopark/Controllers/VehicleController.cs
> +        public ActionResult Details(int id)
Add attibute pls

2022-01-16 19:43 UTC, kuzmiich commented on WebAutopark/Controllers/VehicleController.cs
> +        public ActionResult Index()
add attribute pls.

2022-01-16 19:43 UTC, kuzmiich commented on WebAutopark/Controllers/VehicleController.cs
> +            return selectItems;
U can write this logic using Linq.(optional)

2022-01-16 19:43 UTC, kuzmiich commented on WebAutopark/Controllers/VehicleController.cs
> +        public ActionResult Edit(int id)
add attribute pls

2022-01-16 19:43 UTC, kuzmiich commented on WebAutopark/Controllers/VehicleTypeController.cs
> +        public ActionResult Index()
add attribute pls

2022-01-16 19:43 UTC, kuzmiich commented on WebAutopark/Controllers/VehicleTypeController.cs
> +        public ActionResult Create() => View();
add attribute pls

2022-01-16 19:43 UTC, kuzmiich commented on WebAutopark/Models/OrderItemViewModel.cs
> +        public int Quantity { get; set; }
This prop should be required.

2022-01-16 19:43 UTC, kuzmiich commented on WebAutopark/Models/ComponentViewModel.cs
> +        public string Name { get; set; }
Use `StringLength` attribute to limit length

2022-01-16 19:43 UTC, kuzmiich commented on WebAutopark/Models/VehicleViewModel.cs
> +        [Range(0, 100, ErrorMessage = "FuelConsumption must be between 0 and 100")]
```suggestion
        [Range(0d, 100d, ErrorMessage = "FuelConsumption must be between 0 and 100")]
```

2022-01-16 19:43 UTC, kuzmiich commented on WebAutopark/Models/VehicleViewModel.cs
> +        [Range(0, 1000000, ErrorMessage = "Mileage must be between 0 and 100000")]
```suggestion
        [Range(0d, 1000000d, ErrorMessage = "Mileage must be between 0 and 100000")]
```

2022-01-16 19:43 UTC, kuzmiich commented on WebAutopark/Models/VehicleViewModel.cs
> +        [Range(0, 2500, ErrorMessage = "YearIssue must be between 0 and 2500")]
```suggestion
        [Range(0d, 2500d, ErrorMessage = "YearIssue must be between 0 and 2500")]
```

2022-01-16 19:43 UTC, kuzmiich commented on WebAutopark/Models/VehicleViewModel.cs
> +        [Range(0, 100000, ErrorMessage = "Weight must be between 0 and 100000")]
```suggestion
        [Range(0d, 100000d, ErrorMessage = "Weight must be between 0 and 100000")]
```

2022-01-16 19:43 UTC, kuzmiich commented on WebAutopark/Startup.cs
> +            services.AddAutoMapper(typeof(DtoEntityProfile), typeof(ViewModelDtoProfile));
Better!
Setup profiles using configuration expression

2022-01-16 19:43 UTC, kuzmiich commented on WebAutopark/Controllers/VehicleTypeController.cs
> +        public ActionResult Edit(int id)
add attribute pls

2022-01-16 20:50 UTC, ArtyomKolosov2 commented on WebAutopark.Core/Entities/Vehicle.cs
> +        public int VehicleId { get; set; }
Why? There is already `VehicleTypeId` below

2022-01-16 20:50 UTC, ArtyomKolosov2 commented on WebAutopark/Controllers/VehicleController.cs
> +            IDtoService<VehicleTypeDto> vehicleTypeDtoService)
Nitpick (non-blocking): formatting

2022-01-16 20:50 UTC, ArtyomKolosov2 commented on WebAutopark/Controllers/VehicleController.cs
> +            return selectItems;
Nitpick (non-blocking): add spaces between logical code blocks. And I saw other methods with this problem, please find all other places. It really makes code more readable.

2022-01-16 20:50 UTC, ArtyomKolosov2 commented on WebAutopark/Models/VehicleViewModel.cs
> +        [Range(0, 100000, ErrorMessage = "Weight must be between 0 and 100000")]
Is it really worth the effort? I'm prettey sure that C# compiler is smart enough to handle this automatically. But it will require the effort to find all the places and replace this.

2022-01-16 20:50 UTC, ArtyomKolosov2 commented on WebAutopark/Controllers/VehicleController.cs
> +            return selectItems;
Suggestion: add attribute `[NonAction]` to this method

2022-01-16 20:50 UTC, ArtyomKolosov2 commented on WebAutopark/Models/VehicleViewModel.cs
> +        [Range(0, 100, ErrorMessage = "FuelConsumption must be between 0 and 100")]
https://github.com/Dev-incubator/WebAutopark.Artem_Kondratovich/pull/3#discussion_r785492224

2022-01-16 20:50 UTC, ArtyomKolosov2 commented on WebAutopark/Models/VehicleViewModel.cs
> +        [Range(0, 1000000, ErrorMessage = "Mileage must be between 0 and 100000")]
https://github.com/Dev-incubator/WebAutopark.Artem_Kondratovich/pull/3#discussion_r785492224

2022-01-16 20:50 UTC, ArtyomKolosov2 commented on WebAutopark/Models/VehicleViewModel.cs
> +        [Range(0, 2500, ErrorMessage = "YearIssue must be between 0 and 2500")]
https://github.com/Dev-incubator/WebAutopark.Artem_Kondratovich/pull/3#discussion_r785492224

2022-01-17 09:09 UTC, Kondratovich commented on WebAutopark.Core/Entities/Vehicle.cs
> +        public int VehicleId { get; set; }
In this entity, `VehicleId` is the primary key and `VehicleTypeId` is the foreign key. I see no reason to rename this props.

2022-01-17 09:09 UTC, Kondratovich commented on WebAutopark/Controllers/VehicleController.cs
> +        public ActionResult Create()
fixed

2022-01-17 09:09 UTC, Kondratovich commented on WebAutopark/Controllers/VehicleController.cs
> +        public ActionResult Details(int id)
fixed

2022-01-17 09:09 UTC, Kondratovich commented on WebAutopark/Controllers/VehicleController.cs
> +        public ActionResult Index()
fixed

2022-01-17 09:11 UTC, Kondratovich commented on WebAutopark/Controllers/VehicleController.cs
> +            IDtoService<VehicleTypeDto> vehicleTypeDtoService)
fixed

2022-01-17 09:11 UTC, Kondratovich commented on WebAutopark/Models/OrderItemViewModel.cs
> +        public int Quantity { get; set; }
fixed

2022-01-17 09:11 UTC, Kondratovich commented on WebAutopark/Models/ComponentViewModel.cs
> +        public string Name { get; set; }
fixed

2022-01-17 09:14 UTC, Kondratovich commented on WebAutopark/Controllers/VehicleController.cs
> +            return selectItems;
fixed

2022-01-17 09:26 UTC, kuzmiich commented on WebAutopark.Core/Entities/Vehicle.cs
> +        public int VehicleId { get; set; }
I missed it. You're right.

2022-01-17 10:23 UTC, kuzmiich approved these changes
Good job

2022-01-20 17:22 UTC, PushMeNow requested changes

2022-01-20 17:22 UTC, PushMeNow commented on WebAutopark.Core/Interfaces/IDtoService.cs
> +    public interface IDtoService<T>
IDataService

2022-01-20 17:22 UTC, PushMeNow commented on WebAutopark/Models/OrderItemViewModel.cs
> +        public int? Quantity { get; set; }
Why all these fields are nullable?

2022-01-20 17:46 UTC, Kondratovich commented on WebAutopark.Core/Interfaces/IDtoService.cs
> +    public interface IDtoService<T>
fixed

2022-01-20 17:50 UTC, Kondratovich commented on WebAutopark/Models/OrderItemViewModel.cs
> +        public int? Quantity { get; set; }
On the server, a required value is considered missing if the property is null. A non-nullable field is always valid, and the [Required] attribute's error message is never displayed. To solve this problem MSDN recommends make the field nullable.
https://docs.microsoft.com/en-us/aspnet/core/mvc/models/validation?view=aspnetcore-6.0#required-validation-on-the-server

2022-01-22 11:06 UTC, PushMeNow approved these changes

2022-01-22 11:18 UTC, merged