Fourth week
Dev-incubator/WebAutopark.Artem_Kondratovich pull request #4
Opened 2022-01-23 12:46 UTC by Kondratovich

2022-01-23 17:50 UTC, kuzmiich requested changes

2022-01-23 17:50 UTC, kuzmiich commented on WebAutopark.Core/Interfaces/Repositories/IOrderItemRepository.cs
> +        public IEnumerable<OrderItem> GetItemsByOrderId(int orderId);
```suggestion
        IEnumerable<OrderItem> GetItemsByOrderId(int orderId);
```
Redundant

2022-01-23 17:50 UTC, kuzmiich commented on WebAutopark.Core/Interfaces/Repositories/IOrderRepository.cs
> +        public int CreateAndReturnId(Order item);
```suggestion
        int CreateAndReturnId(Order item);
```
Redundant

2022-01-23 17:50 UTC, kuzmiich commented on WebAutopark.Core/Interfaces/Repositories/IVehicleRepository.cs
> +        public IEnumerable<Vehicle> GetAllSortedItems(SortState sortOrder);
```suggestion
        IEnumerable<Vehicle> GetAllSortedItems(SortState sortOrder);
```
Redundant

2022-01-23 17:50 UTC, kuzmiich commented on WebAutopark.DatabaseAccess/Repositories/OrderItemRepository.cs
> +                                              "FROM OrderItems oi " +
```suggestion
                                              "FROM OrderItems AS oi " +
```

2022-01-23 17:50 UTC, kuzmiich commented on WebAutopark.DatabaseAccess/Repositories/OrderItemRepository.cs
> +                                              "INNER JOIN Components c " +
```suggestion
                                              "INNER JOIN Components AS c " +
```

2022-01-23 17:50 UTC, kuzmiich commented on WebAutopark.DatabaseAccess/Repositories/OrderItemRepository.cs
> +                                                   "FROM OrderItems oi " +
```suggestion
                                                   "FROM OrderItems AS oi " +
```

2022-01-23 17:50 UTC, kuzmiich commented on WebAutopark.DatabaseAccess/Repositories/OrderItemRepository.cs
> +                                                   "INNER JOIN Components c " +
```suggestion
                                                   "INNER JOIN Components  AS c " +
```

2022-01-23 17:50 UTC, kuzmiich commented on WebAutopark.DatabaseAccess/Repositories/OrderItemRepository.cs
> +                                             "INNER JOIN Components c " +
```suggestion
        private const string QueryGetAll = "SELECT oi.*, c.ComponentId as CompId, c.Name " +
                                             "FROM OrderItems AS oi " +
                                             "INNER JOIN Components AS c " +
```

2022-01-23 17:50 UTC, kuzmiich commented on WebAutopark.DatabaseAccess/Repositories/OrderItemRepository.cs
> +                                             "ON oi.ComponentId = c.ComponentId";
```suggestion
                                             "ON oi.ComponentId = CompId";
```

2022-01-23 17:50 UTC, kuzmiich commented on WebAutopark.DatabaseAccess/Repositories/OrderRepository.cs
> +                                             "WHERE OrdersId = @OrdersId";
Check `AS` in queries

2022-01-23 17:50 UTC, kuzmiich commented on WebAutopark.DatabaseAccess/Repositories/VehicleRepository.cs
> +                                              "ON v.VehicleTypeId = vt.VehicleTypeId";
Check `AS` before reduction

2022-01-23 17:50 UTC, kuzmiich commented on WebAutopark.DatabaseAccess/Repositories/VehicleRepository.cs
> +            };
Create additional method.

2022-01-23 17:50 UTC, kuzmiich commented on WebAutopark.Core/Enums/SortState.cs
> +    public enum SortState
Add IdAsc & IdDesc

2022-01-23 17:50 UTC, kuzmiich commented on WebAutopark.DatabaseAccess/Repositories/VehicleRepository.cs
> +                _ => $"{QueryGetAll} ORDER BY Model ASC"
Sort by Id

2022-01-23 17:50 UTC, kuzmiich commented on WebAutopark/Controllers/OrderItemController.cs
> +            ViewBag.Components = GetComponentsForSelect();
Set up ViewBag.Component in this method.
Also rename it to SetComponentsForSelect();
I think it`s better.

2022-01-23 17:50 UTC, kuzmiich commented on WebAutopark/Controllers/VehicleController.cs
> +        public ActionResult Index(SortState sortOrder = SortState.ModelAsc)
By default use sort by Id ascending

2022-01-23 17:50 UTC, kuzmiich commented on WebAutopark/Models/OrderViewModel.cs
> +        public Vehicle Vehicle { get; set; }
Add spaces

2022-01-23 17:50 UTC, kuzmiich commented on WebAutoprk.BusinessLogic/Services/Interfaces/IOrderService.cs
> +        public int CreateAndReturnId(OrderDto item);
```suggestion
        int CreateAndReturnId(OrderDto item);
```
Redundant

2022-01-23 17:50 UTC, kuzmiich commented on WebAutoprk.BusinessLogic/Services/OrderItemService.cs
> +            return dtoItems;
Add spaces

2022-01-23 17:50 UTC, kuzmiich commented on WebAutoprk.BusinessLogic/Services/OrderService.cs
> +            return insertedOrderId;
Add spaces

2022-01-23 17:50 UTC, kuzmiich commented on WebAutoprk.BusinessLogic/Services/VehicleService.cs
> +            return dtoItems;
Add spaces

2022-01-23 19:24 UTC, Kondratovich commented on WebAutoprk.BusinessLogic/Services/VehicleService.cs
> +            return dtoItems;
fixed

2022-01-23 19:24 UTC, Kondratovich commented on WebAutoprk.BusinessLogic/Services/OrderService.cs
> +            return insertedOrderId;
fixed

2022-01-23 19:25 UTC, Kondratovich commented on WebAutoprk.BusinessLogic/Services/Interfaces/IOrderService.cs
> +        public int CreateAndReturnId(OrderDto item);
fixed

2022-01-23 19:25 UTC, Kondratovich commented on WebAutopark/Models/OrderViewModel.cs
> +        public Vehicle Vehicle { get; set; }
fixed

2022-01-23 19:25 UTC, Kondratovich commented on WebAutopark/Controllers/VehicleController.cs
> +        public ActionResult Index(SortState sortOrder = SortState.ModelAsc)
fixed

2022-01-23 19:27 UTC, Kondratovich commented on WebAutopark.DatabaseAccess/Repositories/VehicleRepository.cs
> +                _ => $"{QueryGetAll} ORDER BY Model ASC"
fixed

2022-01-23 19:27 UTC, Kondratovich commented on WebAutopark.DatabaseAccess/Repositories/VehicleRepository.cs
> +            };
fixed

2022-01-23 19:29 UTC, Kondratovich commented on WebAutopark.Core/Interfaces/Repositories/IVehicleRepository.cs
> +        public IEnumerable<Vehicle> GetAllSortedItems(SortState sortOrder);
fixed

2022-01-24 17:52 UTC, PushMeNow approved these changes

2022-01-26 08:44 UTC, merged